spring:
  profiles:
    active: "dev"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/salus"
    username: "salus"
    password: "salus"
    hikari:
      pool-name: SalusPool
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  mail:
    # CAMBIAR A ENV VARS
    from-header: "Project Salus <ua-pracs@kikisito.com>"
    host: "mail.kikisito.com"
    port: 587
    username: "ua-pracs@kikisito.com"
    password: "h1JjbpxjtR4tpKPu#e0OvOwkZvtWLh$8S@q2f3Dc09YiJs1GulW9M2ZF*&vm#4bsVu1GwbJ60G@ErMNb$mmxYHlS3C9Y!yk1Add#Ne#xFPJ#$wNXR5vid^o*HBcCmqC!"
    properties:
      mail:
        debug: true
        smtp:
          from: "ua-pracs@kikisito.com"
          auth: 'true'
          starttls:
            enable: 'true'

application:
  # Cambiar a ENV VARS
  name: "Salus"
  host: http://localhost:8080
  security:
    jwt:
      cookieMaxAge: 604800
      secret-key: "qBcwXDAgtkWw0LL1IY/aIOr/3+EmHPfMhWytjgrUo8FeYDuZaVlRg6A5vh6ETRykYI0wQZpcBSb9OEnCcDNjgw=="
      access-token:
        expiration: 86400 # 1 dia
      refresh-token:
        expiration: 604800 # 7 dias
      password-reset-token:
        expiration: 3600000 # 1 hora