POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DB: salus
POSTGRES_USER: salus
POSTGRES_PASSWORD: salus

MAIL_FROM_HEADER: "Project Salus <ua-pracs@kikisito.com>"
MAIL_HOST: mail.kikisito.com
MAIL_PORT: 587
MAIL_USERNAME: "ua-pracs@kikisito.com"
MAIL_PASSWORD: "h1JjbpxjtR4tpKPu#e0OvOwkZvtWLh$8S@q2f3Dc09YiJs1GulW9M2ZF*&vm#4bsVu1GwbJ60G@ErMNb$mmxYHlS3C9Y!yk1Add#Ne#xFPJ#$wNXR5vid^o*HBcCmqC!"
MAIL_SMTP_FROM: "ua-pracs@kikisito.com"

APP_NAME: "Salus"
APP_HOST: http://localhost:8080
APP_SECRET: "KB6z+5wrQCzu7cALLthZ1rKd1EEL/SI9ANLMwh1yH1M="

spring:
  profiles:
    active: "dev"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    hikari:
      pool-name: SalusPool
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  mail:
    from-header: "${MAIL_FROM_HEADER}"
    host: "${MAIL_HOST}"
    port: "${MAIL_PORT}"
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    properties:
      mail:
        debug: true
        smtp:
          from: "${MAIL_SMTP_FROM}"
          auth: 'true'
          starttls:
            enable: 'true'

application:
  name: "${APP_NAME}"
  host: "${APP_HOST}"
  security:
    jwt:
      secret-key: "${APP_SECRET}"
      access-token:
        expiration: 86400 # 1 dia
      refresh-token:
        expiration: 604800 # 7 dias
      password-reset-token:
        expiration: 3600000 # 1 hora